# Pipeline to run basic code quality tests as part of pull requests.

resources:
    containers:
    - container: mlops
      image: mcr.microsoft.com/mlops/python:latest
  
trigger: none
pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - 'iac/**/*.tf' 
  
pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: "IaC_CI_Pipeline"
    displayName: "IaC CI Pipeline"
    steps:
    # Install dependencies
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
        downloadUrl: 'https://releases.hashicorp.com/terraform/0.13.3/terraform_0.13.3_linux_amd64.zip'
    - task: Bash@3
      displayName: Install tflint
      inputs:
        targetType: 'inline'
        script: |
          curl -L https://github.com/terraform-linters/tflint/releases/download/v0.17.0/tflint_linux_amd64.zip -o tflint.zip
          unzip tflint.zip
          rm tflint.zip
          sudo mv tflint /usr/local/bin \
    # Run checks
    - task: Bash@3
      displayName: Init And Validate Terraform and TFLint
      inputs:
        targetType: 'inline'
        workingDirectory: ./iac
        script: |
          terraform init
          terraform validate
          tflint 
  